In [3]:
import joblib

# Data Processing
import pandas as pd
import numpy as np

# Modelling
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, ConfusionMatrixDisplay
from sklearn.model_selection import RandomizedSearchCV, train_test_split
from scipy.stats import randint
import matplotlib.pyplot as plt

# Tree Visualisation
from sklearn.tree import export_graphviz
from IPython.display import Image
import graphviz
from sklearn.metrics import f1_score
from sklearn import tree

In [4]:
rcf=joblib.load('randomfc.pkl')

In [5]:
df=pd.read_csv('accident_data_mum.csv')

In [6]:
df

,Location Name,Latitude,Longitude,No. of Accident,No. of Fatalities
0,Colaba,19.070492,72.895680,10,5
1,Dadar,19.139944,72.821071,15,7
2,Andheri,19.074142,72.834193,8,3
3,Bandra,19.134322,72.825798,12,4
4,Chembur,19.120213,72.890733,20,8
5,Goregaon,19.131142,72.844253,7,2
6,Kurla,19.060648,72.848990,5,1
7,Malad,19.058694,72.834087,10,4
8,Mulund,18.998331,72.851004,18,6
9,Santacruz,19.038346,72.862792,11,3
10,Vashi,19.048558,72.863947,9,2
11,Versova,19.085730,72.848059,6,2
12,Worli,19.006215,72.830890,14,5
13,Thane,19.056077,72.834701,16,6
14,Powai,19.059664,72.828893,10,4
15,Borivali,19.067791,72.888724,8,3
16,Navi Mumbai,19.039617,72.845415,13,5
17,Juhu,19.063780,72.833042,10,4
18,Lower Parel,19.053597,72.923719,5,2
19,Parel,19.051755,72.921762,12,4
20,Vile Parle,19.074319,72.870999,10,5
21,Bhayandar,19.069659,72.839627,15,7
22,Mira Road,19.116780,72.855014,9,3
23,Dombivli,19.071955,72.869227,7,2
24,Kalyan,19.162052,72.934907,10,4
25,Ghatkopar,19.079954,72.917525,14,5
26,Nerul,19.021971,72.866171,11,3
27,Kharghar,19.056425,72.938067,6,2
28,Panvel,19.038388,72.850957,8,3
29,Kandivali,19.021200,72.872201,12,4
30,Khar,19.165554,72.855615,15,6
31,Marine Lines,19.079245,72.867174,7,2
32,Matunga,19.038982,72.859313,13,5
33,Sion,19.061480,72.828024,9,3
34,Vikhroli,19.083892,72.921125,10,4
35,Byculla,19.144412,72.928342,11,3
36,Mahim,19.048804,72.910276,12,4
37,Wadala,19.055282,72.830828,8,3
38,Govandi,19.154166,72.841659,6,2
39,Kanjurmarg,19.133102,72.856777,10,4
40,Kokilaben Hospital,19.123890,72.897601,14,5
41,Lokhandwala,19.067870,72.910634,17,6
42,Ghatkopar,19.030443,72.867059,12,4
43,Sakinaka,18.998070,72.821989,11,3
44,Ghatkopar,19.134221,72.874362,9,2
45,Kandivali,19.040686,72.841116,13,5
46,Charkop,18.988788,72.833651,15,6
47,Malad West,19.045015,72.863170,8,3
48,Kandivali West,19.085231,72.905324,7,2
49,Goregaon West,19.067592,72.903912,10,4

In [7]:
X=df[["No. of Accident","No. of Fatalities"]]

In [8]:
y_pred=rcf.predict(X)

In [9]:
y_pred

array([1., 1., 1., 1., 2., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
df['Severity']=y_pred

In [11]:
df

,Location Name,Latitude,Longitude,No. of Accident,No. of Fatalities,Severity
0,Colaba,19.070492,72.895680,10,5,1.0
1,Dadar,19.139944,72.821071,15,7,1.0
2,Andheri,19.074142,72.834193,8,3,1.0
3,Bandra,19.134322,72.825798,12,4,1.0
4,Chembur,19.120213,72.890733,20,8,2.0
5,Goregaon,19.131142,72.844253,7,2,1.0
6,Kurla,19.060648,72.848990,5,1,1.0
7,Malad,19.058694,72.834087,10,4,1.0
8,Mulund,18.998331,72.851004,18,6,1.0
9,Santacruz,19.038346,72.862792,11,3,1.0
10,Vashi,19.048558,72.863947,9,2,1.0
11,Versova,19.085730,72.848059,6,2,1.0
12,Worli,19.006215,72.830890,14,5,1.0
13,Thane,19.056077,72.834701,16,6,1.0
14,Powai,19.059664,72.828893,10,4,1.0
15,Borivali,19.067791,72.888724,8,3,1.0
16,Navi Mumbai,19.039617,72.845415,13,5,1.0
17,Juhu,19.063780,72.833042,10,4,1.0
18,Lower Parel,19.053597,72.923719,5,2,1.0
19,Parel,19.051755,72.921762,12,4,1.0
20,Vile Parle,19.074319,72.870999,10,5,1.0
21,Bhayandar,19.069659,72.839627,15,7,1.0
22,Mira Road,19.116780,72.855014,9,3,1.0
23,Dombivli,19.071955,72.869227,7,2,1.0
24,Kalyan,19.162052,72.934907,10,4,1.0
25,Ghatkopar,19.079954,72.917525,14,5,1.0
26,Nerul,19.021971,72.866171,11,3,1.0
27,Kharghar,19.056425,72.938067,6,2,1.0
28,Panvel,19.038388,72.850957,8,3,1.0
29,Kandivali,19.021200,72.872201,12,4,1.0
30,Khar,19.165554,72.855615,15,6,1.0
31,Marine Lines,19.079245,72.867174,7,2,1.0
32,Matunga,19.038982,72.859313,13,5,1.0
33,Sion,19.061480,72.828024,9,3,1.0
34,Vikhroli,19.083892,72.921125,10,4,1.0
35,Byculla,19.144412,72.928342,11,3,1.0
36,Mahim,19.048804,72.910276,12,4,1.0
37,Wadala,19.055282,72.830828,8,3,1.0
38,Govandi,19.154166,72.841659,6,2,1.0
39,Kanjurmarg,19.133102,72.856777,10,4,1.0
40,Kokilaben Hospital,19.123890,72.897601,14,5,1.0
41,Lokhandwala,19.067870,72.910634,17,6,1.0
42,Ghatkopar,19.030443,72.867059,12,4,1.0
43,Sakinaka,18.998070,72.821989,11,3,1.0
44,Ghatkopar,19.134221,72.874362,9,2,1.0
45,Kandivali,19.040686,72.841116,13,5,1.0
46,Charkop,18.988788,72.833651,15,6,1.0
47,Malad West,19.045015,72.863170,8,3,1.0
48,Kandivali West,19.085231,72.905324,7,2,1.0
49,Goregaon West,19.067592,72.903912,10,4,1.0

In [12]:
dfs = {group: df_group for group, df_group in df.groupby('Severity')}

In [13]:
for category, df_category in dfs.items():
    print(f"DataFrame for Category '{category}':")
    print(df_category)
    print("\n")

DataFrame for Category '1.0':
         Location Name   Latitude  Longitude  No. of Accident  \
0               Colaba  19.070492  72.895680               10
1                Dadar  19.139944  72.821071               15
2              Andheri  19.074142  72.834193                8
3               Bandra  19.134322  72.825798               12
5             Goregaon  19.131142  72.844253                7
6                Kurla  19.060648  72.848990                5
7                Malad  19.058694  72.834087               10
8               Mulund  18.998331  72.851004               18
9            Santacruz  19.038346  72.862792               11
10               Vashi  19.048558  72.863947                9
11             Versova  19.085730  72.848059                6
12               Worli  19.006215  72.830890               14
13               Thane  19.056077  72.834701               16
14               Powai  19.059664  72.828893               10
15            Borivali  19.067791  72.888724                8
16         Navi Mumbai  19.039617  72.845415               13
17                Juhu  19.063780  72.833042               10
18         Lower Parel  19.053597  72.923719                5
19               Parel  19.051755  72.921762               12
20          Vile Parle  19.074319  72.870999               10
21           Bhayandar  19.069659  72.839627               15
22           Mira Road  19.116780  72.855014                9
23            Dombivli  19.071955  72.869227                7
24              Kalyan  19.162052  72.934907               10
25           Ghatkopar  19.079954  72.917525               14
26               Nerul  19.021971  72.866171               11
27            Kharghar  19.056425  72.938067                6
28              Panvel  19.038388  72.850957                8
29           Kandivali  19.021200  72.872201               12
30                Khar  19.165554  72.855615               15
31        Marine Lines  19.079245  72.867174                7
32             Matunga  19.038982  72.859313               13
33                Sion  19.061480  72.828024                9
34            Vikhroli  19.083892  72.921125               10
35             Byculla  19.144412  72.928342               11
36               Mahim  19.048804  72.910276               12
37              Wadala  19.055282  72.830828                8
38             Govandi  19.154166  72.841659                6
39          Kanjurmarg  19.133102  72.856777               10
40  Kokilaben Hospital  19.123890  72.897601               14
41         Lokhandwala  19.067870  72.910634               17
42           Ghatkopar  19.030443  72.867059               12
43            Sakinaka  18.998070  72.821989               11
44           Ghatkopar  19.134221  72.874362                9
45           Kandivali  19.040686  72.841116               13
46             Charkop  18.988788  72.833651               15
47          Malad West  19.045015  72.863170                8
48      Kandivali West  19.085231  72.905324                7
49       Goregaon West  19.067592  72.903912               10

    No. of Fatalities  Severity
0                   5       1.0
1                   7       1.0
2                   3       1.0
3                   4       1.0
5                   2       1.0
6                   1       1.0
7                   4       1.0
8                   6       1.0
9                   3       1.0
10                  2       1.0
11                  2       1.0
12                  5       1.0
13                  6       1.0
14                  4       1.0
15                  3       1.0
16                  5       1.0
17                  4       1.0
18                  2       1.0
19                  4       1.0
20                  5       1.0
21                  7       1.0
22                  3       1.0
23                  2       1.0
24                  4       1.0
25                  5       1.0
26                  3       1.0
27                  2       1.0
28                  3       1.0
29                  4       1.0
30                  6       1.0
31                  2       1.0
32                  5       1.0
33                  3       1.0
34                  4       1.0
35                  3       1.0
36                  4       1.0
37                  3       1.0
38                  2       1.0
39                  4       1.0
40                  5       1.0
41                  6       1.0
42                  4       1.0
43                  3       1.0
44                  2       1.0
45                  5       1.0
46                  6       1.0
47                  3       1.0
48                  2       1.0
49                  4       1.0


DataFrame for Category '2.0':
  Location Name   Latitude  Longitude  No. of Accident  No. of Fatalities  \
4       Chembur  19.120213  72.890733               20                  8

   Severity
4       2.0